version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: auction_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: auction_user
      POSTGRES_PASSWORD: auction_pass
      POSTGRES_DB: auction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: